### ISSUE TITLE
Consider adding making decodeMatAsync asyncio compliant

### ISSUE THREAD

**Issue by SimonSchick** [yushulx/python-mrz-scanner-sdk#2]
The current callback pattern is somewhat counter-intuitive and crashes the python runtime when no handler is registered.

<img width="496" alt="image" src="https://github.com/yushulx/python-mrz-scanner-sdk/assets/3259089/b6693705-5417-44c7-8930-e5e7cbf5501b">

**Comment by yushulx** [comment]
@SimonSchick the async method is implemented in C++ thread. It is not an asynchronous coroutine.

**Comment by SimonSchick** [comment]
I understand that, my suggestion is to add it as an alternative and/or change the api.
Plus it most certainly shouldn't be able to crash the python runtime :)

**Comment by yushulx** [comment]
@SimonSchick can you share your code? I can't reproduce your error.

**Comment by SimonSchick** [comment]
I'm rather certain I added the sample to my main post as an edit, it seems it hasn't gone through. Will update soon.
