### ISSUE TITLE
Add type defs?

### ISSUE THREAD

**Issue by SimonSchick** [yushulx/python-mrz-scanner-sdk#3]
We rolled our own but it might be good for customers to have them shipped.

```py
from cv2 import Mat

def initLicense(lic: str) -> None: ...
def createInstance() -> DynamsoftMrzReader: ...
def load_settings() -> str: ...

class MrzResult:
    text: str
    confidence: int
    x1: int
    x2: int
    x3: int
    x4: int
    y1: int
    y2: int
    y3: int
    y4: int

class DynamsoftMrzReader:
    def loadModel(self, model: str) -> None: ...
    def decodeFile(self, path: str) -> list[MrzResult]: ...
    def decodeMat(self, mat: Mat) -> list[MrzResult]: ...
```

See https://peps.python.org/pep-0561/

**Comment by yushulx** [comment]
@SimonSchick Thanks for your good suggestion. Would you like to submit a pull request? 😄

**Comment by SimonSchick** [comment]
Potentially, the issue is resolved for _us_ and I have a ton of stuff on my plate, but you might want to make your API more accessible for other paying customers? :P
