### ISSUE TITLE
Is this package considered *official*?

### ISSUE THREAD

**Issue by SimonSchick** [yushulx/python-mrz-scanner-sdk#4]
3rd time's a charm but I was asked by our eng manage wether this package is considered official or not, I understand you are a Dynamsoft employee, any reason this SDK is not hosted under the dynamsoft org?

The primary worry here is supply chain and security considerations.

Thanks!

**Comment by yushulx** [comment]
@SimonSchick It's an open source project created by myself. You can check the code for security consideration. Why not hosted under the dynamsoft org? Please contact support@dynamsoft.com. I'm not the decision maker, unfortunately :(

**Comment by yushulx** [comment]
@SimonSchick The official package is online now. Please visit [dynamsoft-capture-vision-bundle](https://pypi.org/project/dynamsoft-capture-vision-bundle/)
