### ISSUE TITLE
setup.py ext_args is not defined when sys.platform == "darwin"

### ISSUE THREAD

**Issue by jaclyn-zhong** [yushulx/python-mrz-scanner-sdk#5]
Hello!

I'm encountering a bug in `setup.py` when trying to build on a Mac where [on this line](https://github.com/yushulx/python-mrz-scanner-sdk/blob/main/setup.py#L36), `ext_args` is not defined.

Full error message:
```
  Collecting mrz-scanner-sdk==1.1.0 (from -r requirements-base.in (line 40))
    Using cached mrz-scanner-sdk-1.1.0.tar.gz (21.4 MB)
    Preparing metadata (setup.py) ... error
    error: subprocess-exited-with-error
    
    × python setup.py egg_info did not run successfully.
    │ exit code: 1
    ╰─> [6 lines of output]
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/private/var/folders/gc/46tfyxxn07d24zpxzq1r7cc00000gp/T/pip-resolve-5jtmdgxo/mrz-scanner-sdk_d5cc7f9b19694c0bb175a787cd3b94c6/setup.py", line 36, in <module>
            'mrzscanner', ['src/mrzscanner.cpp'], **ext_args)
        NameError: name 'ext_args' is not defined
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
```

This seems to be because `ext_args` is only defined for `linux`/`linux2` on this [preceding line](https://github.com/yushulx/python-mrz-scanner-sdk/blob/main/setup.py#L22) (not when `sys.platform == "darwin"`)

Could you help resolve? Thanks!

**Comment by yushulx** [comment]
@jaclyn-zhong Thanks for your feedback. Unfortunately, this package does not support macOS. It relies on platform-specific shared libraries.

![image](https://github.com/user-attachments/assets/0c5f746b-756a-4ab3-9a94-337e18e59eb8)

**Comment by yushulx** [comment]
@jaclyn-zhong The official [dynamsoft-capture-vision-bundle](https://pypi.org/project/dynamsoft-capture-vision-bundle/) with **macOS** support is now available. If you are still interested in recognizing MRZ on macOS, please try the [sample code](https://github.com/yushulx/python-mrz-scanner-sdk/tree/main/examples/official).
